name: 'My Composite Action'
description: 'This action does something'
outputs:
  matrix:
    description: 'The result of the action'
    value: ${{ steps.set-result.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Set result
      is: set-result
      shell: bash
      run: |
        value="a\nb\nc"
        result=$(echo "$value" | cut -d'/' -f1 | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
        echo "result=$result" >> $GITHUB_OUTPUT

