name: sample

run-name: My Composite Action

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sample
        id: my-action
      - name: Use the output
        run: |
            for i in ${{ steps.my-action.outputs.matrix }}; do
                echo $i
            done
